### ISSUE TITLE
pull request url broken in Contributing.md

### ISSUE THREAD

**Issue by mikezawitkowski** [cliqz-oss/local-sheriff#2]
In the `Contributing.md` file the link for bullet 4 on how submitting a pull request sends me to this page https://help.github.com/articles/proposing-changes-to-a-project-with-pull-requests/ and shows me a 404 error with the message "Whoops, looks like that page doesn't exist."

**Comment by konarkmodi** [comment]
@mikezawitkowski : I think the link on Github does not exist anymore. If I remember correctly, I wanted to put the link around these lines: `https://help.github.com/enterprise/2.7/user/articles/proposing-changes-to-a-project-with-pull-requests/` , do you want to issue a PR with the edited link?

**Comment by mikezawitkowski** [comment]
Sure, I'll work on that today

**Comment by mikezawitkowski** [comment]
PR submitted, you should be all set!
